### ISSUE TITLE
Docker arcblock/abtnode 在Mac OS上运行404

### ISSUE THREAD

**Issue by shenxiuqiang** [ArcBlock/abt-node-issues#1]
如何在Mac OS上运行 docker镜像？

docker run -d -p 80:80 -p 443:443  -v /Users/edz/data/abtnode:/data/abtnode arcblock/abtnode

访问 http://localhost/ 404

![image](https://user-images.githubusercontent.com/1235258/103149392-e9a3ce80-47a3-11eb-8493-ccfecbebf0b8.png)

**Comment by shenxiuqiang** [comment]
![image](https://user-images.githubusercontent.com/1235258/103149268-e52ae600-47a2-11eb-993a-9e178830a816.png)

**Comment by polunzh** [comment]
现在首页确实是 404, 下个版本会修改默认的地址。

**Comment by shenxiuqiang** [comment]
如果是局域网通过ip访问：http://{ip}/admin/welcome

**Comment by shenxiuqiang** [comment]
Blockchain Manager 启动错误
![image](https://user-images.githubusercontent.com/1235258/103330823-27ec0700-4a9e-11eb-92af-c6dd20faad95.png)
![image](https://user-images.githubusercontent.com/1235258/103330834-32a69c00-4a9e-11eb-8faf-ef2b1e7caaf3.png)

错误日志：

[2020-12-30 04:53:54] [error] [@abtnode/core:blocklet:manager] "ensure endpoint healthy failed" {"endpoint":"http://127.0.0.1:8090/","minConsecutiveTime":5000,"timeout":10000}

[2020-12-30 04:53:54] [error] [@abtnode/core:blocklet:manager] "start blocklet failed" {"did":"z8iZn18zGRm5veEdhmrS2FRrUyw5ZAQcewVMH","name":"blockchain-manager"}

[2020-12-30 04:53:54] [error] [@abtnode/core:blocklet:manager] "check blocklet if started failed" {"did":"z8iZn18zGRm5veEdhmrS2FRrUyw5ZAQcewVMH","appId":"blockchain-manager","ports":{"BLOCKLET_PORT":8090,"FORGE_WEB_PORT":8091},"context":{"protocol":"http","user":{"did":"z1TP1dqVV4R9Q5TaHxXAdjLEZfgFGoH6jYC","pk":"z2HRh9o6MQQAidShdTxpNWGU4T2DY4uEsnx4J5XaaAPeZ","name":"Hiker","role":"owner","approved":true,"bid":null},"url":"/api/gql","query":{},"hostname":"10.252.72.162","port":0},"timeout":10000,"error":"the service is not ready within 5 seconds, please check your network","error_stack":"Error: the service is not ready within 5 seconds, please check your network\n    at ensureStarted (/home/arcblock/.local/lib/node_modules/@abtnode/cli/node_modules/@abtnode/util/lib/ensure-endpoint-healthy.js:25:13)\n    at async /home/arcblock/.local/lib/node_modules/@abtnode/cli/node_modules/@abtnode/util/lib/ensure-endpoint-healthy.js:66:5\n    at async /home/arcblock/.local/lib/node_modules/@abtnode/cli/node_modules/@abtnode/util/lib/try-with-timeout.js:13:22"}

**Comment by shenxiuqiang** [comment]
blocklet manager启动超时失败添加 --env BLOCKLET_START_TIMEOUT=60 参数：
docker run -d -p 80:80 -p 443:443 --env BLOCKLET_START_TIMEOUT=60  -v /Users/edz/data/abtnode:/data/abtnode arcblock/abtnode

**Comment by polunzh** [comment]
@shenxiuqiang 最新版 v1.1.9 已经修改了默认页面, 有兴趣可以更新下: npm install -g @abtnode/cli

**Comment by polunzh** [comment]
或者在 "设置>基础设置" 页面中选中 “开启 Welcome 页面":
![image](https://user-images.githubusercontent.com/4244426/103498379-84c13600-4e7f-11eb-842f-e6fd00fd7a42.png)

**Comment by shenxiuqiang** [comment]
done
